feature: add NewNATSMessageHandlerV2
kumparan/kumnats pull request #19
Opened 2020-07-24 09:11 UTC by miun173

2020-07-24 09:15 UTC, zhenqianz commented on v2/kumnats.go
> +			err = errHandler(payload, msg.Subject)
ini maunya dibedain subjectnya, kalo bisa didefine sama si servicenya

2020-07-27 02:43 UTC, aslamhadi commented on v2/kumnats.go
> +func NewNATSMessageHandlerV2(payload MessagePayload, retryAttempts int, retryInterval time.Duration, lambda func(payload MessagePayload) error, errHandler Handler) stan.MsgHandler {
`NewNATSMessageWithErrorHandler` ?

2020-07-27 04:27 UTC, zhenqianz requested changes

2020-07-27 04:27 UTC, zhenqianz commented on v2/kumnats.go
> +	MessageErrorHandler func(objectID int64) error
ini ttp pake payload aja mi, soalnya belum tentu id nya bakal int64, dan mungkin event nya ga butuh cuma id

2020-07-27 04:27 UTC, zhenqianz commented on v2/kumnats.go
> +	MessageErrorHandler func(objectID int64) error
message handler harusnya ttp ```func(payload MessagePayload) error```

2020-07-27 04:29 UTC, miun173 commented on v2/kumnats.go
> +	MessageErrorHandler func(objectID int64) error
oh, okee

2020-07-27 04:33 UTC, aslamhadi commented on v2/kumnats.go
> +		if err != nil {
ini bukannya masuk ke line 209 dibawahnya `errHandler` ya?

2020-07-27 06:21 UTC, zhenqianz requested changes

2020-07-27 06:21 UTC, zhenqianz commented on v2/kumnats.go
> +		if err != nil {
mi ini error give up nya maunya di print dulu, baru masukin ke errHandler. dan kalo bisa masukin ke error handler nya di log warn juga

2020-07-27 06:43 UTC, aslamhadi commented on v2/kumnats.go
> +		logrus.Warn("handling ErrGiveUpProcessingMessagePayload")
tambahin payloadnya di sini mu

2020-07-27 06:54 UTC, zhenqianz approved these changes

2020-07-27 06:57 UTC, aslamhadi approved these changes

2020-08-06 03:34 UTC, merged